'use client';

import { useSession } from '@/context/SessionContext';
import { useRef } from 'react';

const COMMITMENT_LABELS = {
  pricing: 'Pricing Lock',
  policy: 'Policy Lock',
  distribution: 'Distribution Lock',
};

export function DecisionMemo() {
  const { session, resetSession, setCurrentRoom } = useSession();
  const memoRef = useRef<HTMLDivElement>(null);

  const { room1, room2, room3, room4 } = session;

  // Generate a headline from the category leap (first 10 words)
  const generateHeadline = () => {
    const words = room2.categoryLeap.split(' ').slice(0, 10);
    return words.join(' ') + (room2.categoryLeap.split(' ').length > 10 ? '...' : '');
  };

  const handleDownload = () => {
    const memo = `# THE DECISION MEMO
Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}

---

## HEADLINE
${generateHeadline()}

---

## THE THREAT (From The Detox)

### The Industry Lie
${room1.theLie}

### The Sacred Cow
${room1.theSacredCow}

### The Pre-Mortem (Why We Failed in 2028)
${room1.thePreMortem}

---

## THE VISION (From The Elevation)

### The Envy
${room2.theEnvy}

### The Unfair Advantage
${room2.theUnfairAdvantage}

### The Category Leap
${room2.categoryLeap}

---

## THE MECHANICS (The Leverage Map)

| Component | Definition |
|-----------|------------|
| Customer Change | ${room3.customerChange} |
| Mechanism | ${room3.mechanism} |
| Moat | ${room3.moat} |
| Trade-off | ${room3.tradeOff} |

---

## THE BLOOD PRICE (From The Commitment)

### One-Way Door: ${room4.oneWayDoor ? COMMITMENT_LABELS[room4.oneWayDoor] : 'Not Selected'}

### The Kill List
1. ${room4.killList[0]}
2. ${room4.killList[1]}
3. ${room4.killList[2]}

### Budget Reallocation
${room4.budgetToken}

---

*This document represents an irreversible strategic commitment.*
*Generated by The Commitment Engine*
`;

    const blob = new Blob([memo], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `decision-memo-${new Date().toISOString().split('T')[0]}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleStartOver = () => {
    if (confirm('Are you sure you want to start over? This will clear all your progress.')) {
      resetSession();
      setCurrentRoom(1);
    }
  };

  return (
    <div className="min-h-screen room-5 text-[var(--room-fg)]">
      <div className="max-w-4xl mx-auto px-4 py-12">
        {/* Header */}
        <div className="text-center mb-12 animate-fade-in">
          <p className="text-sm uppercase tracking-widest text-[var(--room-muted)] mb-4">
            The Commitment Engine
          </p>
          <h1 className="text-5xl font-serif font-bold mb-4">The Decision Memo</h1>
          <p className="text-[var(--room-muted)]">
            Your irreversible strategic commitment
          </p>
        </div>

        {/* The Memo */}
        <div ref={memoRef} className="bg-white rounded-lg shadow-2xl border border-[var(--room-border)] overflow-hidden">
          {/* Memo Header */}
          <div className="bg-[var(--room-fg)] text-white p-8">
            <p className="text-sm uppercase tracking-widest opacity-60 mb-4">Headline</p>
            <h2 className="text-2xl font-serif font-medium leading-tight">
              {generateHeadline()}
            </h2>
            <p className="text-sm opacity-60 mt-4">
              {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
            </p>
          </div>

          {/* Memo Content */}
          <div className="p-8 space-y-8">
            {/* The Threat */}
            <section>
              <h3 className="text-lg font-semibold text-[var(--room-accent)] uppercase tracking-wider mb-4 flex items-center gap-2">
                <span className="w-8 h-0.5 bg-[var(--room-accent)]"></span>
                The Threat
              </h3>
              <div className="grid gap-4">
                <div className="p-4 bg-gray-50 rounded-lg">
                  <p className="text-xs uppercase tracking-wider text-[var(--room-muted)] mb-1">The Industry Lie</p>
                  <p className="text-sm">{room1.theLie}</p>
                </div>
                <div className="p-4 bg-gray-50 rounded-lg">
                  <p className="text-xs uppercase tracking-wider text-[var(--room-muted)] mb-1">The Sacred Cow</p>
                  <p className="text-sm">{room1.theSacredCow}</p>
                </div>
                <div className="p-4 bg-gray-50 rounded-lg">
                  <p className="text-xs uppercase tracking-wider text-[var(--room-muted)] mb-1">Pre-Mortem: 2028</p>
                  <p className="text-sm">{room1.thePreMortem}</p>
                </div>
              </div>
            </section>

            {/* The Vision */}
            <section>
              <h3 className="text-lg font-semibold text-[var(--room-accent)] uppercase tracking-wider mb-4 flex items-center gap-2">
                <span className="w-8 h-0.5 bg-[var(--room-accent)]"></span>
                The Vision
              </h3>
              <div className="grid md:grid-cols-2 gap-4 mb-4">
                <div className="p-4 bg-gray-50 rounded-lg">
                  <p className="text-xs uppercase tracking-wider text-[var(--room-muted)] mb-1">The Envy</p>
                  <p className="text-sm">{room2.theEnvy}</p>
                </div>
                <div className="p-4 bg-gray-50 rounded-lg">
                  <p className="text-xs uppercase tracking-wider text-[var(--room-muted)] mb-1">The Unfair Advantage</p>
                  <p className="text-sm">{room2.theUnfairAdvantage}</p>
                </div>
              </div>
              <div className="p-6 bg-[var(--room-fg)] text-white rounded-lg">
                <p className="text-xs uppercase tracking-wider opacity-60 mb-2">The Category Leap</p>
                <p className="text-lg font-serif italic">&ldquo;{room2.categoryLeap}&rdquo;</p>
              </div>
            </section>

            {/* The Mechanics */}
            <section>
              <h3 className="text-lg font-semibold text-[var(--room-accent)] uppercase tracking-wider mb-4 flex items-center gap-2">
                <span className="w-8 h-0.5 bg-[var(--room-accent)]"></span>
                The Mechanics
              </h3>
              <div className="grid md:grid-cols-2 gap-4">
                <div className="p-4 border border-[var(--room-border)] rounded-lg">
                  <p className="text-xs uppercase tracking-wider text-[var(--room-muted)] mb-1">Customer Change</p>
                  <p className="text-sm">{room3.customerChange}</p>
                </div>
                <div className="p-4 border border-[var(--room-border)] rounded-lg">
                  <p className="text-xs uppercase tracking-wider text-[var(--room-muted)] mb-1">Mechanism</p>
                  <p className="text-sm">{room3.mechanism}</p>
                </div>
                <div className="p-4 border border-[var(--room-border)] rounded-lg">
                  <p className="text-xs uppercase tracking-wider text-[var(--room-muted)] mb-1">Moat</p>
                  <p className="text-sm">{room3.moat}</p>
                </div>
                <div className="p-4 border border-[var(--room-border)] rounded-lg">
                  <p className="text-xs uppercase tracking-wider text-[var(--room-muted)] mb-1">Trade-off</p>
                  <p className="text-sm">{room3.tradeOff}</p>
                </div>
              </div>
            </section>

            {/* The Blood Price */}
            <section>
              <h3 className="text-lg font-semibold text-red-600 uppercase tracking-wider mb-4 flex items-center gap-2">
                <span className="w-8 h-0.5 bg-red-600"></span>
                The Blood Price
              </h3>

              {/* One-Way Door */}
              <div className="p-4 bg-red-50 border border-red-200 rounded-lg mb-4">
                <p className="text-xs uppercase tracking-wider text-red-600 mb-1">One-Way Door</p>
                <p className="text-lg font-semibold text-red-800">
                  {room4.oneWayDoor ? COMMITMENT_LABELS[room4.oneWayDoor] : 'Not Selected'}
                </p>
              </div>

              {/* Kill List */}
              <div className="p-4 bg-gray-50 rounded-lg mb-4">
                <p className="text-xs uppercase tracking-wider text-[var(--room-muted)] mb-3">The Kill List</p>
                <ol className="space-y-2">
                  {room4.killList.map((item, index) => (
                    <li key={index} className="flex items-start gap-3 text-sm">
                      <span className="text-red-600 font-bold">{index + 1}.</span>
                      <span className="line-through opacity-70">{item}</span>
                    </li>
                  ))}
                </ol>
              </div>

              {/* Budget Token */}
              <div className="p-4 bg-gray-50 rounded-lg">
                <p className="text-xs uppercase tracking-wider text-[var(--room-muted)] mb-1">Budget Reallocation</p>
                <p className="text-sm font-medium">{room4.budgetToken}</p>
              </div>
            </section>
          </div>

          {/* Memo Footer */}
          <div className="border-t border-[var(--room-border)] p-6 text-center">
            <p className="text-xs text-[var(--room-muted)] italic">
              This document represents an irreversible strategic commitment.
            </p>
            <p className="text-xs text-[var(--room-muted)] mt-1">
              Generated by The Commitment Engine
            </p>
          </div>
        </div>

        {/* Actions */}
        <div className="flex flex-col sm:flex-row gap-4 justify-center mt-8">
          <button
            onClick={handleDownload}
            className="px-8 py-3 bg-[var(--room-fg)] text-white rounded-lg font-medium hover:opacity-90 transition-opacity"
          >
            Download Memo (.md)
          </button>
          <button
            onClick={handleStartOver}
            className="px-8 py-3 border border-[var(--room-border)] rounded-lg font-medium hover:bg-gray-50 transition-colors"
          >
            Start New Session
          </button>
        </div>
      </div>
    </div>
  );
}
